### ISSUE TITLE
Problem running on Visual Studio

### ISSUE THREAD

**Issue by klayt421** [jameslahm/wargame#4]
These problem raised after I git cloned into my local machine. 
``` 
1>D:\Source\wargame-master\WarGame.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss
1>D:\Source\wargame-master\WarGame.h(133,1): error C2447: '{': missing function header (old-style formal list?)
1>D:\Source\wargame-master\WarGame.h(142,1): error C2447: '{': missing function header (old-style formal list?)
1>D:\Source\wargame-master\WarGame.h(166,1): error C2447: '{': missing function header (old-style formal list?)
1>D:\Source\wargame-master\WarGame.cpp(1700,1): fatal error C1004: unexpected end-of-file found
```

**Comment by jameslahm** [comment]
Hi, the errors show that your default code page is 936, not `utf-8`. You can reference https://stackoverflow.com/questions/41335199/how-to-config-visual-studio-to-use-utf-8-as-the-default-encoding-for-all-project to set default encoding for your visual studio. And https://en.wikipedia.org/wiki/Unicode_in_Microsoft_Windows#UTF-8, https://stackoverflow.com/questions/56419639/what-does-beta-use-unicode-utf-8-for-worldwide-language-support-actually-do#:~:text=In%20some%20Windows%2010%20builds,8%20for%20worldwide%20language%20support%22 may help.

**Comment by klayt421** [comment]
1>WarGame.rc(112): error RC2135: file not found: E:\projects\c\
1>Done building project "WarGame.vcxproj" -- FAILED.

```
IDB_PNG1                PNG                     "E:\\projects\\c\\程序设计基础\\code\\src\\WarGame\\res\\help1.png"   //This line of code is causing the error
```

This is the warning I recevied after saving the files as UTF8-with signature. There are even more problems when I save it as UT8-without signature.

**Comment by klayt421** [comment]
Ran in successfully on my computer after changing the directory route! Thank you!
